FROM apache/hive:3.1.3

WORKDIR /opt


USER root
# Install wget
RUN apt-get update && apt-get install -y wget

# Add all required dependencies
RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar -P /opt/hive/lib/ && \
    wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar -P /opt/hive/lib/ && \
    wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.3.6/hadoop-common-3.3.6.jar -P /opt/hive/lib/ && \
    wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client/3.3.6/hadoop-client-3.3.6.jar -P /opt/hive/lib/ && \
    wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.6/hadoop-client-runtime-3.3.6.jar -P /opt/hive/lib/ && \
    wget https://repo1.maven.org/maven2/com/google/guava/guava/27.0-jre/guava-27.0-jre.jar -P /opt/hive/lib/ && \
    wget https://jdbc.postgresql.org/download/postgresql-42.2.27.jar -P /opt/hive/lib/


USER hive
EXPOSE 9083

ENTRYPOINT ["bash", "/entrypoint.sh"]